version: '3.9'
services:
  backend:
    build: ./backend
    ports:
      - "8000:8000"
    environment:
      - DATABASE_URL=${DATABASE_URL:-postgresql://postgres:password@host.docker.internal:5432/heliumdb}
      - SECRET_KEY=${SECRET_KEY:-supersecretkey}
      - PORT=8000
    extra_hosts:
      - "host.docker.internal:host-gateway"
  frontend:
    build: ./frontend
    ports:
      - "5000:5000"
    depends_on:
      - backend
    environment:
      - NODE_ENV=development
